apiVersion: v1
kind: Secret
metadata:
  name: dropship-secrets
  labels:
    app: dropship-backend
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgrespassword"
  DATABASE_URL: "postgresql+psycopg2://postgres:postgrespassword@postgres-service:5432/dropship_db"
